In [1]:
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.animation as animation

In [2]:
plt.rcParams['figure.dpi'] = 300
plt.rcParams['savefig.dpi'] = 300

three body structure (two dimensions)
<img src="./figure/question.png" alt="Drawing" style="width: 200px;"/>
https://www.khanacademy.org/science/ap-biology/chemistry-of-life/structure-of-water-and-hydrogen-bonding/a/hs-water-and-life-review

In [16]:
# System #

'''
H1:1
H2:2
O:3
'''

# Stiffness #
KOH1 = 10
KOH2 = 10

#LOH1 = 0.5
#LOH2 = 0.5

stiffness_list = np.array([KOH1,KOH2])
#spring_length_list = np.array([LOH1,L0H2])


# Mass #
MH1 = 1
MH2 = 1
MO = 16

mass_list = np.array([MH1,MH2,MO])

# Position #
PH1 = [0,0]
PH2 = [2,0]
PO = [0.5,1.5]

position_list = np.array([PH1,PH2,PO])

# Bond list #

bond_list = np.array([[0,2],[1,2]])


In [17]:
def bond_stiffness(k,m1,m2):
    return np.array([[k/(m1**0.5*m1**0.5),0,-k/(m1**0.5*m2**0.5),0],[0,k/(m1**0.5*m1**0.5),0,-k/(m1**0.5*m2**0.5)],[-k/(m1**0.5*m2**0.5),0,k/(m2**0.5*m2**0.5),0],[0,-k/(m1**0.5*m2**0.5),0,k/(m2**0.5*m2**0.5)]])

In [18]:
def hessian(m_list,p_list,b_list,k_list):
    hm = np.zeros((m_list.shape[0]*2,m_list.shape[0]*2))
    
    num_cout = 0
    for i,j in bond_list*2:

        k_n = bond_stiffness(k_list[num_cout],m_list[int(i/2)],m_list[int(j/2)])
        print(k_n)
        hm[i,i:i+2] += k_n[0,0:2]
        hm[i,j:j+2] += k_n[0,2:4]
        
        hm[i+1,i:i+2] += k_n[1,0:2]
        hm[i+1,j:j+2] += k_n[1,2:4]
        
        hm[j,i:i+2] += k_n[2,0:2]
        hm[j,j:j+2] += k_n[2,2:4]
        
        hm[j+1,i:i+2] += k_n[3,0:2]
        hm[j+1,j:j+2] += k_n[3,2:4]
        
 
    return hm

In [19]:
system_kmatrix = hessian(mass_list,position_list,bond_list,stiffness_list)

[[10.     0.    -2.5    0.   ]
 [ 0.    10.     0.    -2.5  ]
 [-2.5    0.     0.625  0.   ]
 [ 0.    -2.5    0.     0.625]]
[[10.     0.    -2.5    0.   ]
 [ 0.    10.     0.    -2.5  ]
 [-2.5    0.     0.625  0.   ]
 [ 0.    -2.5    0.     0.625]]


In [20]:
print(system_kmatrix)

[[10.    0.    0.    0.   -2.5   0.  ]
 [ 0.   10.    0.    0.    0.   -2.5 ]
 [ 0.    0.   10.    0.   -2.5   0.  ]
 [ 0.    0.    0.   10.    0.   -2.5 ]
 [-2.5   0.   -2.5   0.    1.25  0.  ]
 [ 0.   -2.5   0.   -2.5   0.    1.25]]


In [8]:
system_val, system_vec = np.linalg.eig(system_kmatrix)

In [9]:
system_val

array([  0. , 100. , 112.5,   0. , 100. , 112.5])

In [10]:
system_vec

array([[ 2.35702260e-01, -7.07106781e-01,  6.66666667e-01,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [-0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         2.35702260e-01,  7.07106781e-01,  6.66666667e-01],
       [ 2.35702260e-01,  7.07106781e-01,  6.66666667e-01,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [-0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         2.35702260e-01, -7.07106781e-01,  6.66666667e-01],
       [ 9.42809042e-01, -1.22450471e-15, -3.33333333e-01,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [-0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         9.42809042e-01, -1.22450471e-15, -3.33333333e-01]])

In [11]:
modeshape = system_vec[[2,3,4]]

In [12]:
(2**0.5*4**0.5)

2.8284271247461903

In [13]:
'''
import matplotlib.pyplot as plt
import matplotlib.animation as animation

fig, ax = plt.subplots()  # 建立單一圖表
ax.set_xlim(0,10)         # 設定 x 軸範圍 0～10
ax.set_ylim(0,10)         # 設定 y 軸範圍 0～10

def init():
    ax.scatter(2, 8)      # 一開始要執行的韓式，在 (2,8) 的位置畫點

def run(data):
    if data>0:
        ax.scatter(data, data)    # 如果資料大於 0，就在圖表上畫點
    else:
        pass

ani = animation.FuncAnimation(fig, run, frames=10, interval=10, init_func=init)  # 製作動畫
ani.save('animation.gif', fps=10)   # 儲存為 gif
plt.show()
'''

"\nimport matplotlib.pyplot as plt\nimport matplotlib.animation as animation\n\nfig, ax = plt.subplots()  # 建立單一圖表\nax.set_xlim(0,10)         # 設定 x 軸範圍 0～10\nax.set_ylim(0,10)         # 設定 y 軸範圍 0～10\n\ndef init():\n    ax.scatter(2, 8)      # 一開始要執行的韓式，在 (2,8) 的位置畫點\n\ndef run(data):\n    if data>0:\n        ax.scatter(data, data)    # 如果資料大於 0，就在圖表上畫點\n    else:\n        pass\n\nani = animation.FuncAnimation(fig, run, frames=10, interval=10, init_func=init)  # 製作動畫\nani.save('animation.gif', fps=10)   # 儲存為 gif\nplt.show()\n"